### ISSUE TITLE
getting started 

### ISSUE THREAD

**Issue by cameliakazisncf** [MAIF/melusine#111]
Hello, I am writing this report hoping for some help.
I have been trying to work on your projet for a while but have had difficulties due to a proxy on my laptop. The solution found to install le Melusine librairy was to charge all the librairies on another laptop and then copy them on mine. 
I have yet to finish the installation of jupyter so hen I finally had access to melusine I ran some tests to make sure it was working well so I wrote a .py file with the code below and ran it in my terminal and had the error in the screenshot below.
I don't understand the error so I wanted to know if the problem was with how I installed melusine or with the fact that I didn't have jupyter yet.

from melusine.data.data_loader import load_email_data
df_emails = load_email_data()
print(df_emails[1])

- 
![Capture d’écran 2021-11-22 153201](https://user-images.githubusercontent.com/94908707/143027394-5d2105f9-b130-4580-b59e-fdd5129abca0.png)

- I am using python 3.8
- I am on Windows

**Python version** :

**Melusine version** :

**Operating System** :

**Comment by TFA-MAIF** [comment]
Hi!

Thank you for your interest and the detailled issue. 
As melusine uses dataframes, you should use .loc ou .iloc to extract lines from your object df_emails.

Ex: df_emails.loc[1]

you can find more information on https://pandas.pydata.org/docs/reference/frame.html to learn how to manipulate pandas objects. 

Let me know if this solves your issue. 
Best regards.
Tiphaine

**Comment by cameliakazisncf** [comment]
Hello !

Thank you for your fast and accurate answer.

I have finished installing jupyter so I can finally start working on the tutorials.
Unfortunately I have ran into an error not of my doing, in the tutorial14 for exchange : 


ImportError: cannot import name 'ExchangeConnector' from 'melusine.connectors' (c:\users\sckl10211\appdata\local\programs\python\python38\lib\site-packages\melusine\connectors\__init__.py)

Thank you again for your help

**Comment by hugo-quantmetry** [comment]
Hello Camelia,
Just seen your reply sorry,
You might be using an older version of melusine without the ExchangeConnector,
Can you try 
pip install --upgrade melusine
?

Best

**Comment by hugo-quantmetry** [comment]
Closing the issue, feel free to re-open it if needed
