### ISSUE TITLE
text_body error with our server version

### ISSUE THREAD

**Issue by Maxime-POULAIN-Verlingue** [MAIF/melusine#113]
Hey !

We had an issue when we tried to get the mails from the mailbox server using get_emails. It seems it's once again due to the version of our mailbox server.

<img width="405" alt="Capture_error_get_emails" src="https://user-images.githubusercontent.com/94903022/143064308-0b3e3b91-64f1-455f-a555-896229b96ce5.PNG">

It seems that the text_body atribute is not available for the older version of Exchange. To fix that, we made two changes in melusine/connectors/exchange.py : 

![image](https://user-images.githubusercontent.com/94903022/143065126-c216a684-99aa-4b0b-9e8c-77dc84aa38c5.png)

**Mailbox Server** : Microsoft Exchange Server 2010

**Python version** : 3.8.12

**Melusine version** : 2.3.1

**Operating System** : Windows

**Comment by TFA-MAIF** [comment]
Hi Maxime, thank you for highlighting this issue of compatibility.
If you would like to see this integrated, would you be willing to submit a pull request? 

The code in screenshot would need some adjustment to be retrocompatible with different versions of Exchange so "body" value should be parametrable. 

For example, 
if text_body lead to error or is missing:
    try body

or check Exchange version (if possible) and get the correct value in consequences

Looking forward to your PR.
Best regards

**Comment by Maxime-POULAIN-Verlingue** [comment]
Hi !

Sorry for the late reply. 
Our company has upgraded the version of Exchange that we used.
We don't have this error with the new version, so I haven't developed a PR.

Best regards
