### ISSUE TITLE
Issue with attachment type metadata

### ISSUE THREAD

**Issue by Maxime-POULAIN-Verlingue** [MAIF/melusine#115]
Hey !

We had a problem with the attachment type in metadata. As you can see in the screenshot below, we had only two values after applying our Metadata pipeline. 0 for the presence of an attachment file and 1 if there is no attachment  file in the mail. The screenshot is an extract of the DataFrame call df_email.

![dfemails_error_metadata](https://user-images.githubusercontent.com/94903022/143248166-5fdab6aa-d59a-44ea-9006-595f68ed1b8e.PNG)

Here is the way we create our pipeline and how we apply it on our emails : 

> Metadatapipeline = Pipeline([('MetaExtension', MetaExtension()), 
>                               ('MetaDate', MetaDate()), 
>                               ('MetaAttachmentType', MetaAttachmentType()),
>                               ('Dummifier', Dummifier(columns_to_dummify = ['extension', 'attachment_type', 'dayofweek','hour', 'min']))])
> df_meta = Metadatapipeline.fit_transform(df_emails)

Then, this is the function which is supposed to extract the type of the attachment file in melusine/prepare_email/metadata_engineering.py: 
![image](https://user-images.githubusercontent.com/94903022/143231575-ccd1f665-dfe5-4fa7-b4df-c027abacaed4.png)
![image](https://user-images.githubusercontent.com/94903022/143231323-d3cd20f5-241b-4f7f-af86-4a7793f95d07.png)

We added some prints to understand what is the problem. As you can see, when there is at least one attachment file in the mail, the type of x is str, and when there is no attachment file the value of x is nan.  
When the function has to deal with a mail with an attachment file, the value of the row["attachment"] is a str. For example, we could have "['image002.png', 'image003.jpg']". Then, the for loop will just take it as a str and deal with the char one by one. This seems to be the reason of our issue.

To fix this problem, we did : 
![image](https://user-images.githubusercontent.com/94903022/143251235-cc27487b-b40f-45a5-9852-1e87260c56b0.png)

This seems to solve our issue : 
![image](https://user-images.githubusercontent.com/94903022/143251460-10f8c72c-36e9-4ece-9303-e7a314dafd4b.png)
![image](https://user-images.githubusercontent.com/94903022/143251620-65873ce9-5888-440b-b334-2746bd5fa446.png)

**Python version** : 3.8.12

**Melusine version** : 2.3.1

**Operating System** : Windows

**Comment by TFA-MAIF** [comment]
Hi Maxime, 

We are currently working on refactoring Melusine and this might be too early to integrate. 
We keep your suggestion in mind but will put it on hold at the moment. 

Best regards

**Comment by Maxime-POULAIN-Verlingue** [comment]
Hey !

I downloaded the last version of Melusine (2.3.4) and It seems I don't have this issue anymore with the new version.
I close this issue.

Best regards
