### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by CameliaSNCF** [MAIF/melusine#126]
**Python version** : 3.8.10

**Melusine version** : 2.3.2

**Operating System** : Windows

Hello,
I would like to implement the technique of cross-validation to validate my results with the neural network but I have this error : 

![erreur1](https://user-images.githubusercontent.com/95216688/153840960-57b6f300-2f56-479b-b03e-42907906e538.png)

![erreur2](https://user-images.githubusercontent.com/95216688/153840997-e92542e2-3aa7-4d3e-aca8-05901f5757c9.png)

Is Melusine not compatible with cross_val ? 

Best regards,
Camelia

**Comment by CameliaSNCF** [comment]
Here is how I initialize the model for reference : 

![erreur3](https://user-images.githubusercontent.com/95216688/154064760-a9882c84-d65e-4716-b9a1-5d4ffbfc69b2.png)

**Comment by CameliaSNCF** [comment]
This issue has been resolved, there was an error in the melusine code : "self.bert_tokenizer=bert_tokenizer" was missing from NeuralModel.init()

Best regards
Camelia

**Comment by TFA-MAIF** [comment]
Hello Camelia, 

Thank you for this interesting remark. 
As we are going through modifications for the new version, we will try to add this fix. 

Best regards
