### ISSUE TITLE
Wrapping lemmatizers 

### ISSUE THREAD

**Issue by adam-benjellounSG** [MAIF/melusine#127]
Hello Melusine Team,

As discussed together, here is our issue before the pull request for our lemmatizers wrappers.

We would like to contribute to Melusine with different lemmatizers wrapped in sklearn transformers objects.

**Overview of the Solution**:
We wrapped in a sklearn transformer object the different lemmatizers provided by Spacy s well as Lefff lemmatizer.
These objects are compatible with the TransformerScheduler as well as sklearn pipelines.

Best Regards,

**Comment by TFA-MAIF** [comment]
Hello!!

Looking forward to your pull request!

Best regards,
Tiphaine

**Comment by TFA-MAIF** [comment]
PR merged. We will integrate it to a new version and tutorials.
