### ISSUE TITLE
loading a model

### ISSUE THREAD

**Issue by CameliaSNCF** [MAIF/melusine#130]
Hey there and thank you for using Issue Tracker!

**Python version** :  3.8.10

**Melusine version** :  2.3.2

**Operating System** :  Windows

Hello, I am trying to save a model and then load it and test it in another notebook.
Unfortunately I can't find any exammple of this process in your documentation and I can't figure out how to load the model properly and keep having an error.

![savedModel1](https://user-images.githubusercontent.com/95216688/160129618-fb579619-c876-44cd-85cf-8ce73348ce56.png)

![savedModel2](https://user-images.githubusercontent.com/95216688/160129642-0ded1cca-d4fe-4e16-9f1d-98f4f8919b55.png)

![savedModel3](https://user-images.githubusercontent.com/95216688/160129652-1e262dbc-8332-42e6-a334-af32f2bdba12.png)

Could you give me some pointers ?

Best regards,
Camelia.

**Comment by TFA-MAIF** [comment]
Hello Camelia, 

I will be working on the library next week. I will take a look at your issue then except if someone answers you before. 

Have a good week-end. 
Best regards,
Tiphaine

**Comment by hugo-quantmetry** [comment]
Hello Camelia,
I think I know where your problem comes from.
Could you try the solution suggested in this issue ?
https://github.com/MAIF/melusine/issues/89

```
import joblib
model.save_nn_model("MY_MODEL")
joblib.dump(model, "MY_MODEL.pkl", compress=True)

loaded_model = joblib.load("MY_MODEL.pkl")
loaded_model.load_nn_model("MY_MODEL")
```

The way Melusine models should be saved is not obvious, sorry about that

**Comment by hugo-quantmetry** [comment]
Closing the issue for now,
Feel free to re-open it if needed
