### ISSUE TITLE
Setup.py miss  `melusine/config/config/config.json`

### ISSUE THREAD

**Issue by PerrierRemi** [MAIF/melusine#138]
When installing with `pip`, `melusine/config/config/conf.json` is missing.

![image](https://user-images.githubusercontent.com/57212723/163362613-9c02f14e-943a-41a3-9eea-55cfaa1506ec.png)

Because glob in `setup.py` only capture JSON files in sub-folders of `config`, and skip JSON files in `config` folder itself.

Can be fixed by using `glob.glob("melusine/config/**/*.json", recursive=True)` instead of `glob.glob("melusine/config/**/*.json")`.
I will create a pull request for this issue.

![image](https://user-images.githubusercontent.com/57212723/163363101-462e33eb-f223-419f-9efa-cba708bb1a0a.png)

**Comment by hugo-quantmetry** [comment]
Well spotted !
Deltas between the pypi package and the github repo are tricky oO

We'll make the update
