### ISSUE TITLE
Make the dummifier more flexible

### ISSUE THREAD

**Issue by ghost** [MAIF/melusine#140]
Hi !

If we want to use new metadata like it's explained in tutorials, we may need to modify the dummifier object.

If we have metadata with a type list, we need to modify the code of the Dummifier to be able to use our new metadata, like it's done in the list of attachment type.
![image](https://user-images.githubusercontent.com/86673601/164038167-0bf10193-7666-4e2c-867b-f721745b800f.png)
For example, this is the actual code of the fit() method from the Dummifier: 
![image](https://user-images.githubusercontent.com/86673601/164040943-bd597325-5e13-440e-8ad1-63466195112f.png)

In our case, I wanted to add the name of receivers in metadata used for the training of our model.
To do it, I needed to create the case, in the Dummifier object, where we have a column receivers in df_emails.
It was not very clean, so I made modifications on the Dummifier object to make it more flexible.

In the PR that I will link, we have a new parameter for the Dummifier object, which is a list of the columns with a type list.
Then, we apply the same functions on these columns.

I hope I was clear.

Best regards,

Maxime

**Python version** : 3.9.7

**Melusine version** : 2.3.4

**Operating System** : Windows

**Comment by HugoPerrier** [comment]
New melusine v3.0.0 is out.
Closing legacy issues
