### ISSUE TITLE
The get_meta return no columns in tutorial_7

### ISSUE THREAD

**Issue by benoitLebreton-perso** [MAIF/melusine#143]
- Are you using Mac, Linux or Windows?
Linux
**Python version** :
Python 3.7.10
**Melusine version** :
latest

Hello Melusine,

I face a problem with the `_get_meta` method but I think I have a solution.

`_get_meta()` function does not work because the columns are never selected at the following line https://github.com/MAIF/melusine/blob/10424aaad749327c9ec405802adcb967c41a168f/melusine/models/train.py#L571-L573

indeed each element of `column_list` has '__' at the end because of the following (to select the dummified columns only) https://github.com/MAIF/melusine/blob/10424aaad749327c9ec405802adcb967c41a168f/melusine/models/train.py#L564

On the following image I'm using the debugger in the `tutorial_7_models.ipynb` with a breakpoint in the `_get_meta` method
And we can see that even if we want to use : `meta_input_list=['extension','attachment_type', 'dayofweek', 'hour', 'min']`, 
meta_input_list is empty and it is because we don't have the dummified columns (we have the original columns).
<img width="615" alt="image" src="https://user-images.githubusercontent.com/51739671/186279300-c0e8d5f9-82af-47a6-88f9-ba26a86695b6.png">

This is all because the columns are not Dummyfied at this step and it should be
(to have [`extension__1`, `extension__2`, ...] columns)
In this case, this tutorial is missing an important step : the encoding of the meta 

In fact there is no problem in `tutorial09_full_pipeline_quick.ipynb` because it has dummified the meta. 

So I suggest : 
A/ either we assume the tutorial07 is not using meta and we set `meta_input_list=[]
B/ or we should add the Meta columns to the dataset for this tutorial

Sentiments mutualistes ;)

**Comment by benoitLebreton-perso** [comment]
Maybe, is it because the columns are not Dummyfied at this step and it should be to work ? 
In order to have [`extension__1`, `extension__2`, ...] columns
In this case, this tutorial is missing an important step : the encoding of the meta

**Comment by HugoPerrier** [comment]
New melusine v3.0.0 is out.
Closing legacy issues
