### ISSUE TITLE
structure_email crashes because empty since build_historic give an empty text --> {text:""}

### ISSUE THREAD

**Issue by aagostinelli86** [MAIF/melusine#149]
Hello, I cannot get rid of this error with the following recalamation. I tried to update the congif but it did not work (I added Expéditeur  in transition_list). I think there should be a control/warning to signal an empty "text"  as result  of build_historic(row).  

Any idea ? Is this due to the config file that need to be updated  in a different way ? thanks a lot

"Expéditeur : Moi Reçu le : 04/01/2021 à 14:08:15  Bonjour,  Dans votre message ci-dessous, vous attirez notre attention sur un chèque n'apparaissant pas au crédit de votre compte.  Afin de pouvoir répondre au mieux à votre demande, nous avons besoin des éléments suivants :  - le nom de l'émetteur - le nom et l'adresse de la banque - le numéro de la formule de chèque - la copie lisible du bordereau de dépôt \xa0  Restant à votre disposition, nous vous remercions de votre confiance.  Cordialement,  La Banque Postale  La Banque Postale - Société Anonyme à Directoire et Conseil de Surveillance au capital de 6 585 350 218 euros Siège social et adresse postale : 115, rue de Sèvres - 75 275 Paris Cedex 06 RCS Paris 421 100 645 - Code APE 6419Z, intermédiaire d'assurance, immatriculé à l'ORIAS sous le n° 07 023 424  De : NAME SURNAME Le : 31 décembre 2020 18:55:30  Objet : Dépot de chèques  Bonsoir, et bonnes fêtes ! Je me permets de vous contacter car j'ai fait un dépôt de chèques le 19/12/20 d'un montant de 1954,15 euros à l'Agence Postale de Drap (06). A ce jour mon compte n'a toujours pas été crédité. Pourriez-vous s'il vous plait faire de recherches pour résoudre ce soucis. Merci et meilleurs vœux. NAME SURNAME;"

![image](https://user-images.githubusercontent.com/16646417/211058902-87cf13c7-de89-45d5-94e6-19ee195f445a.png)

![image](https://user-images.githubusercontent.com/16646417/211059684-f96ccca0-94af-490c-ab9f-f701b7d648fc.png)

**Comment by aagostinelli86** [comment]
@TFA-MAIF  as you see, all the text  goes in the "meta" Key

**Comment by HugoPerrier** [comment]
New melusine v3.0.0 is out.
Closing legacy issues
