### ISSUE TITLE
Non-existent TransformerScheduler class

### ISSUE THREAD

**Issue by ghost** [MAIF/melusine#153]
Hello,

I've encountered an issue when trying to use the transformer_scheduler class as referenced in the README.md file of the repository. The documentation suggests using this class as part of the preprocessing pipeline setup example, but I cannot find the actual class implementation in the codebase.

Steps to Reproduce:

Look through the README.md file and attempt the Pre Processing pipeline snippet.
Attempt to locate the transformer_scheduler class in the repository.

Expected Behavior:
The transformer_scheduler class should be found within the repository or the documentation should provide accurate guidance on how to access this class.

Actual Behavior:
The transformer_scheduler class is not present in the repository, and there is no indication that it is part of an external dependency.

Screenshots: 
<img width="746" alt="transformer_scheduler" src="https://github.com/MAIF/melusine/assets/153607178/fef76ec1-870c-4f27-ab4d-e2d2ca3b2d77">
<img width="350" alt="transformer_scheduler2" src="https://github.com/MAIF/melusine/assets/153607178/cfd8054a-39c6-430c-8e98-5d31c523bf0c">

Python Version: 3.9.17 
Operating System: Windows 11

**Comment by HugoPerrier** [comment]
Hello Maxim and thank you for your interest in melusine.

You tried melusine just a few days too early, we have very recently (2 days ago) published a brand new melusine (actually a FULL rewrite).
The code and the docs have been updated but not the Readme yet.

Please have a look at the documentation at 
https://maif.github.io/melusine/ (Work in progress). You'll find guidance and working tutorials.

Let us know if you see any issue.
Hugo

**Comment by MaximCarbonell** [comment]
Hi Hugo! I appreciate the update. I'll reference the github.io website more and do some testing. 

Maxim

**Comment by mjcarbonell** [comment]
Hi Hugo, I just checked the Getting Started page https://maif.github.io/melusine/ and the code samples are completely blank.

**Comment by HugoPerrier** [comment]
Thank you for the heads up,
The root folder for the tutorial code was wrong indeed.
Now you should be able to see it on https://maif.github.io/melusine/tutorials/00_GettingStarted/
