### ISSUE TITLE
train.py "clean_text" should be text_input_column from init

### ISSUE THREAD

**Issue by LuisBlanche** [MAIF/melusine#63]
When using NeuralModel with a dataframe that does not have a 'clean_text' column name (ex: on 'clean_body') it will send an error.

https://github.com/MAIF/melusine/blob/553eb4067a8227b2b65b5a0e992cac8a3166b7c6/melusine/models/train.py#L421-L423

**Comment by TFA-MAIF** [comment]
Thank you Luis for this notification. We just merged a fix.
