### ISSUE TITLE
Tensorflow NotImplementedError error with Camembert

### ISSUE THREAD

**Issue by Kirire** [MAIF/melusine#67]
Hi,

I think I have detected a bug when we want to save the model (save_nn_model / load_nn_model) in the melusine.models.train module with the pretrained Camembert hidden layer. I received a Python NotImplementedError error from Tensorflow library (from get_config). I think this is because TFCamembertModel is a Subclass Networks and isn't a Graph Networks. It seems there are answers in this [topic](https://github.com/huggingface/transformers/issues/2733).

Best regards

**Comment by TFA-MAIF** [comment]
Hi, 

Thank you so much for finding a bug! We'll take a look as quickly as possible and fix it.

Best regards

**Comment by TFA-MAIF** [comment]
Hi @Kirire, we released Melusine 2.2.5 last week and it should fix this issue. The current transformers library does not allow to use the keras save function at its full potential. We implemented a work around. I will close this issue now.
