### ISSUE TITLE
Generic datetime is not handled

### ISSUE THREAD

**Issue by DataFactory-Verlingue** [MAIF/melusine#92]
Hi !
There is an issue with this type of datetime : 2021-06-24T13:02:43+00:00 in the 'date' column. Indeed, in MetaDate class you expect the date to have this format : `regex_date_format=r"\w+ (\d+) (\w+) (\d{4}) (\d{2}) h (\d{2})" `. In case of our date does not fit the format, the except return the raw format so we could expect it continue but in fact the to_datetime just after expect the format : `date_format="%d/%m/%Y %H:%M" `. In our case, to_datetime :
```
 pd.to_datetime(X['date'],
                format=self.date_format,
                infer_datetime_format=False,
                errors="coerce",
            )

```
 return NaT

**Python version** :
3.7
**Melusine version** :
2.3.1
**Operating System** :
Windows 10

**Comment by hugo-quantmetry** [comment]
Merci @DataFactory-Verlingue pour votre contribution à Melusine :)
